version: '3.9'

services:
  voice_playback_app:
    build:
      context: .  # Build the Docker image from the current directory
      dockerfile: Dockerfile  # Use the specified Dockerfile
    ports:
      - "8000:8000"  # Map the container's port 8000 to the host's port 8000
    volumes:
      - ./app:/app:cached  # Map the local `app` directory to the container's `/app` directory with better performance
    environment:
      # Example of additional environment variables:
      # APP_ENV: production
      # API_KEY: your_api_key
    deploy:
      resources:
        limits:
          # Limit the container to 1 CPU
           # Limit the container to 512 MB of memory
    command: ["uvicorn", "app.main_file:app", "--host", "0.0.0.0", "--port", "8000"]
