version: '3.8'

services:
  voice_playback_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map the container's port 8000 to the host's port 8000
    volumes:
      - ./app:/app  # Map the local `app` directory to the container's `/app` directory
    environment:
      # Add environment variables here, if needed
      # Example: API_KEY=your_api_key
    command: ["uvicorn", "app.main_file:app", "--host", "0.0.0.0", "--port", "8000"]
